services:
  - type: web
    name: webspun
    runtime: node
    plan: free
    buildCommand: npm --prefix client install && npm --prefix client run build && npm --prefix server install
    startCommand: npm --prefix server start
    healthCheckPath: /healthz
